// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go-linux-s390x-bootstrap`
const TheVersion = `devel +c501b71 Fri Apr 22 02:15:29 2016 -0400`
const Goexperiment = ``
const StackGuardMultiplier = 1

